name: tastify_food_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.7
  dio: ^5.8.0+1
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^3.0.0
  go_router: ^15.1.1
  hooks_riverpod: ^2.6.1
  http: ^1.3.0
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/full_sized.png
    - assets/animations/loading.json
